-- Supabase SQL for Unbl0cked Zone community chat/posts with custom username/password auth.
-- Passwords are handled by Supabase Auth and are never stored in readable form.
-- Run this in Supabase Dashboard > SQL Editor after creating the project.
-- Re-run this file after updates; it is written to be mostly safe to run more than once.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text unique,
  display_name text not null default 'Member' check (char_length(display_name) between 2 and 24),
  role text not null default 'member' check (role in ('owner','admin','mod','member','banned')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists display_name text not null default 'Member';
alter table public.profiles add column if not exists role text not null default 'member';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
create unique index if not exists profiles_username_unique on public.profiles (lower(username));

create table if not exists public.role_grants (
  username text primary key,
  role text not null check (role in ('owner','admin','mod','member','banned')),
  note text,
  created_at timestamptz not null default now()
);

create or replace function public.current_role()
returns text
language sql
security definer
stable
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'member')
$$;

create or replace function public.set_profile_identity()
returns trigger
language plpgsql
security definer
as $$
declare
  jwt_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  jwt_username text := lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'username', split_part(jwt_email, '@', 1)));
  granted_role text;
begin
  if tg_op = 'INSERT' then
    new.email := jwt_email;
    if coalesce(new.username, '') = '' then
      new.username := jwt_username;
    end if;
  else
    new.email := old.email;
    new.username := old.username;
  end if;

  select rg.role into granted_role from public.role_grants rg where lower(rg.username) = lower(new.username);

  if tg_op = 'INSERT' then
    new.role := coalesce(granted_role, 'member');
  elsif new.role is distinct from old.role and public.current_role() = 'owner' then
    new.role := new.role;
  else
    new.role := coalesce(granted_role, old.role);
  end if;
  return new;
end;
$$;

drop trigger if exists set_profile_identity_trigger on public.profiles;
create trigger set_profile_identity_trigger
before insert or update on public.profiles
for each row execute function public.set_profile_identity();

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.chat_messages add column if not exists updated_at timestamptz;
alter table public.chat_messages add column if not exists deleted_at timestamptz;
alter table public.chat_messages add column if not exists deleted_body text;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.posts add column if not exists updated_at timestamptz not null default now();
alter table public.profiles add column if not exists banned_until timestamptz;
alter table public.profiles add column if not exists muted_until timestamptz;
alter table public.profiles add column if not exists kicked_at timestamptz;
alter table public.profiles add column if not exists kicked_until timestamptz;
alter table public.profiles add column if not exists warnings integer not null default 0;
alter table public.profiles add column if not exists staff_note text;
alter table public.profiles add column if not exists last_seen timestamptz;

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_id uuid references public.profiles(id) on delete cascade,
  action text not null check (action in ('warn','mute','unmute','kick','ban','unban','set_role','delete_account')),
  reason text,
  duration_minutes integer,
  created_at timestamptz not null default now()
);

alter table public.moderation_actions drop constraint if exists moderation_actions_action_check;
alter table public.moderation_actions add constraint moderation_actions_action_check check (action in ('warn','mute','unmute','kick','ban','unban','set_role','delete_account'));

alter table public.moderation_actions enable row level security;

drop policy if exists "staff can read moderation actions" on public.moderation_actions;
drop policy if exists "staff can insert moderation actions" on public.moderation_actions;
create policy "staff can read moderation actions" on public.moderation_actions for select using (public.current_role() in ('owner','admin','mod'));
create policy "staff can insert moderation actions" on public.moderation_actions for insert with check (public.current_role() in ('owner','admin','mod'));

create or replace function public.moderate_user(target_username text, action_name text, reason_text text default null, duration_minutes integer default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_role text;
  target public.profiles%rowtype;
  until_time timestamptz;
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;

  actor_role := public.current_role();
  if actor_role not in ('owner','admin','mod') then
    raise exception 'staff role required';
  end if;

  select * into target from public.profiles where lower(username) = lower(target_username) limit 1;
  if target.id is null then
    raise exception 'target user not found';
  end if;

  if action_name in ('ban','unban') and actor_role <> 'owner' then
    raise exception 'owner role required for ban commands';
  end if;

  if target.role = 'owner' and action_name in ('ban','kick','delete_account') then
    raise exception 'owner accounts cannot be targeted by this command';
  end if;

  if actor_role = 'mod' and target.role in ('owner','admin','mod') then
    raise exception 'mods cannot moderate staff';
  end if;
  if actor_role = 'admin' and target.role = 'owner' then
    raise exception 'admins cannot moderate owners';
  end if;
  if actor_role = 'mod' and action_name not in ('warn','mute','unmute') then
    raise exception 'mods can only warn, mute, or unmute';
  end if;
  if actor_role = 'admin' and action_name not in ('warn','mute','unmute','kick') then
    raise exception 'admins can only warn, mute, unmute, or kick';
  end if;

  if action_name in ('mute','ban','kick') then
    until_time := case when duration_minutes is null or duration_minutes <= 0 then now() + interval '100 years' else now() + make_interval(mins => duration_minutes) end;
  end if;

  if action_name = 'warn' then
    update public.profiles set warnings = warnings + 1, staff_note = reason_text where id = target.id;
  elsif action_name = 'mute' then
    update public.profiles set muted_until = until_time, staff_note = reason_text where id = target.id;
  elsif action_name = 'unmute' then
    update public.profiles set muted_until = null, staff_note = reason_text where id = target.id;
  elsif action_name = 'ban' then
    delete from public.role_grants where lower(username) = lower(target.username);
    update public.profiles set role = 'banned', banned_until = until_time, staff_note = reason_text where id = target.id;
  elsif action_name = 'unban' then
    delete from public.role_grants where lower(username) = lower(target.username);
    update public.profiles set role = 'member', banned_until = null, staff_note = reason_text where id = target.id;
  elsif action_name = 'kick' then
    update public.profiles set kicked_at = now(), kicked_until = until_time, staff_note = reason_text where id = target.id;
  else
    raise exception 'unknown moderation action';
  end if;

  insert into public.moderation_actions(actor_id, target_id, action, reason, duration_minutes)
  values (auth.uid(), target.id, action_name, reason_text, duration_minutes);
end;
$$;

revoke all on function public.moderate_user(text, text, text, integer) from public;
grant execute on function public.moderate_user(text, text, text, integer) to authenticated;

create or replace function public.set_user_role(target_username text, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  if public.current_role() <> 'owner' then
    raise exception 'owner role required';
  end if;
  if new_role not in ('owner','admin','mod','member','banned') then
    raise exception 'invalid role';
  end if;
  select * into target from public.profiles where lower(username) = lower(target_username) limit 1;
  if target.id is null then
    raise exception 'target user not found';
  end if;
  if target.id = auth.uid() then
    raise exception 'owners cannot change their own role here';
  end if;
  if target.role = 'owner' and new_role <> 'owner' then
    raise exception 'owner accounts cannot be demoted here';
  end if;
  if new_role = 'banned' then
    delete from public.role_grants where lower(username) = lower(target.username);
    update public.profiles
    set role = 'banned', banned_until = now() + interval '100 years', muted_until = null, kicked_until = null
    where id = target.id;
  else
    insert into public.role_grants(username, role) values (target.username, new_role)
    on conflict (username) do update set role = excluded.role;
    update public.profiles
    set role = new_role, banned_until = null
    where id = target.id;
  end if;
  insert into public.moderation_actions(actor_id, target_id, action, reason)
  values (auth.uid(), target.id, 'set_role', 'role=' || new_role);
end;
$$;

revoke all on function public.set_user_role(text, text) from public;
grant execute on function public.set_user_role(text, text) to authenticated;

create or replace function public.delete_user_by_username(target_username text)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target public.profiles%rowtype;
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  if public.current_role() <> 'owner' then
    raise exception 'owner role required';
  end if;
  select * into target from public.profiles where lower(username) = lower(target_username) limit 1;
  if target.id is null then
    raise exception 'target user not found';
  end if;
  if target.id = auth.uid() then
    raise exception 'use Delete account for your own account';
  end if;
  if target.role = 'owner' then
    raise exception 'owner accounts cannot be deleted from the member list';
  end if;
  insert into public.moderation_actions(actor_id, target_id, action, reason)
  values (auth.uid(), target.id, 'delete_account', 'owner deleted account');
  delete from auth.users where id = target.id;
end;
$$;

revoke all on function public.delete_user_by_username(text) from public;
grant execute on function public.delete_user_by_username(text) to authenticated;

alter table public.profiles enable row level security;
alter table public.role_grants enable row level security;
alter table public.chat_messages enable row level security;
alter table public.posts enable row level security;

drop policy if exists "profiles readable" on public.profiles;
drop policy if exists "users insert own profile" on public.profiles;
drop policy if exists "users update own display name" on public.profiles;
drop policy if exists "owners update roles" on public.profiles;
drop policy if exists "role grants readable by owners" on public.role_grants;
drop policy if exists "owners manage role grants" on public.role_grants;
drop policy if exists "chat readable" on public.chat_messages;
drop policy if exists "signed in users can chat" on public.chat_messages;
drop policy if exists "users can edit own chat" on public.chat_messages;
drop policy if exists "admins can soft delete chat" on public.chat_messages;
drop policy if exists "posts readable" on public.posts;
drop policy if exists "owners can post" on public.posts;
drop policy if exists "staff can create posts" on public.posts;
drop policy if exists "staff can update posts" on public.posts;
drop policy if exists "staff can delete posts" on public.posts;

create policy "profiles readable" on public.profiles for select using (true);
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own display name" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "owners update roles" on public.profiles for update using (public.current_role() = 'owner') with check (public.current_role() = 'owner');

create policy "role grants readable by owners" on public.role_grants for select using (public.current_role() = 'owner');
create policy "owners manage role grants" on public.role_grants for all using (public.current_role() = 'owner') with check (public.current_role() = 'owner');

create policy "chat readable" on public.chat_messages for select using (public.current_role() in ('owner','admin','mod') or exists (select 1 from public.profiles p where p.id = auth.uid() and coalesce(p.banned_until, now() - interval '1 minute') < now()));
create policy "signed in users can chat" on public.chat_messages for insert with check (
  auth.uid() = user_id and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin','mod','member') and coalesce(p.banned_until, now() - interval '1 minute') < now() and coalesce(p.muted_until, now() - interval '1 minute') < now())
);
create policy "users can edit own chat" on public.chat_messages for update using (
  auth.uid() = user_id
  and deleted_at is null
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin','mod','member') and coalesce(p.banned_until, now() - interval '1 minute') < now() and coalesce(p.muted_until, now() - interval '1 minute') < now())
) with check (
  auth.uid() = user_id
  and deleted_at is null
);
create policy "admins can soft delete chat" on public.chat_messages for update using (
  public.current_role() in ('owner','admin')
) with check (
  public.current_role() in ('owner','admin')
);

create policy "posts readable" on public.posts for select using (public.current_role() in ('owner','admin','mod') or exists (select 1 from public.profiles p where p.id = auth.uid() and coalesce(p.banned_until, now() - interval '1 minute') < now()));
create policy "staff can create posts" on public.posts for insert with check (
  auth.uid() = user_id and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and coalesce(p.banned_until, now() - interval '1 minute') < now()
      and coalesce(p.muted_until, now() - interval '1 minute') < now()
      and (
        p.role in ('owner','admin','mod')
        or (p.role = 'member' and (lower(title) like '[settings]%' or lower(title) like '[suggestions]%'))
      )
  )
);
create policy "staff can update posts" on public.posts for update using (
  public.current_role() in ('owner','admin') or (public.current_role() = 'mod' and auth.uid() = user_id)
) with check (
  public.current_role() in ('owner','admin') or (public.current_role() = 'mod' and auth.uid() = user_id)
);
create policy "staff can delete posts" on public.posts for delete using (
  public.current_role() in ('owner','admin') or (public.current_role() = 'mod' and auth.uid() = user_id)
);

do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.posts;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;

-- To setup roles do:

-- ////////////////////////////////////////////////////////////////

-- update public.profiles
-- set role = 'ROLE'
-- where lower(username) = lower('USERNAME');

-- ////////////////////////////////////////////////////////////////

update public.profiles
set role = 'owner'
where lower(username) = lower('billy41');

create or replace function public.delete_current_user()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_current_user() from public;
grant execute on function public.delete_current_user() to authenticated;
